<?php
$title = 'Bind Resources with roles';
$this->headTitle($title);
/*
  ?>
  <h1>All Node</h1>
  <?php
  if (!empty($allNode)) {
  foreach ($allNode as $data) {
  ?>
  <a href="<?php echo $this->url($data); ?>"><?php echo $this->translate($data); ?></a><br>
  <?php
  }
  }
  ?>
  <h1>Existing resources</h1>
  <?php
  if (!empty($resources)) {
  foreach ($resources as $data) {
  ?>
  <a href="<?php //echo $this->url($data);  ?>"><?php echo $this->translate($data->getName()); ?></a><br>
  <?php
  }
  }
 *
 */
?>
<div class="row">
    <div class="span6">
        <h2>New added resource(s)</h2>
        <?php
        if (!empty($newly_added)) {
            foreach ($newly_added as $data) {
                ?>
                <a href="<?php echo $this->url($data); ?>"><?php echo $this->translate($data); ?></a><br>
                <?php
            }
        }
        ?>
    </div>
    <div class="span6">
        <h2>Delete deleted resource(s)</h2>
        <?php
        if (!empty($delete_from_exist)) {
            foreach ($delete_from_exist as $data) {
                ?>
                <a href="<?php //echo $this->url($data);   ?>"><?php echo $this->translate($data); ?></a><br>
                <?php
            }
        }
        ?>
    </div>
</div>